name: Continous Integration

on:
  # Check that the static website is buildable for every PR
  pull_request:

jobs:
  astro:
    name: 'Build Astro 🚀'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 26
          cache: npm
          cache-dependency-path: astro/package-lock.json
      - run: npm --prefix astro ci
      - run: npm --prefix astro run build
